services:
  broker:
    image: apache/kafka:3.8.0
    container_name: broker
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: FAST://0.0.0.0:9092,SLOWER://0.0.0.0:9093,SLOWEST://0.0.0.0:9094,KRAFT://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: FAST://127.0.0.1:9092,SLOWER://127.0.0.1:9093,SLOWEST://127.0.0.1:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: KRAFT
      KAFKA_INTER_BROKER_LISTENER_NAME: FAST
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: FAST:PLAINTEXT,SLOWER:PLAINTEXT,SLOWEST:PLAINTEXT,KRAFT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
